apiVersion: v2
name: dj-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.3.2
    repository: https://charts.bitnami.com/bitnami
