kind: Secret
apiVersion: v1
metadata:
  name: {{ template "dj-chart.fullname" . }}-api-secret
  labels:
    component: api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ required "secrets.DJANGO_SECRET_KEY" .Values.secrets.DJANGO_SECRET_KEY | quote }}

  # Database
  {{- if .Values.postgresql.enabled }}
  DATABASE_HOST: {{ include "postgresql.primary.fullname" . }}
  DATABASE_PORT: {{ .Values.postgresql.service.port | quote }}
  DATABASE_USER: {{ .Values.postgresql.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  DATABASE_NAME: {{ .Values.postgresql.auth.database | quote }}
  {{- else }}
  DATABASE_NAME: {{ required "secrets.DATABASE_NAME" .Values.secrets.DATABASE_NAME | quote }}
  DATABASE_USER: {{ required "secrets.DATABASE_USER" .Values.secrets.DATABASE_USER | quote }}
  DATABASE_PASSWORD: {{ required "secrets.DATABASE_PASSWORD" .Values.secrets.DATABASE_PASSWORD | quote }}
  DATABASE_HOST: {{ required "secrets.DATABASE_HOST" .Values.secrets.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ required "secrets.DATABASE_PORT" .Values.secrets.DATABASE_PORT | quote }}
  {{- end }} 
